In [19]:
import matplotlib.pyplot as plt
import matplotlib.axes as axes
import numpy as np
import networkx as nx

from qiskit import Aer
from qiskit.tools.visualization import plot_histogram
from qiskit.circuit.library import TwoLocal
from qiskit_optimization.applications import Maxcut, Tsp
from qiskit.algorithms import VQE, NumPyMinimumEigensolver
from qiskit.algorithms.optimizers import SPSA
from qiskit.utils import algorithm_globals, QuantumInstance
from qiskit_optimization.algorithms import MinimumEigenOptimizer
from qiskit_optimization.problems import QuadraticProgram

In [20]:
# Generating a graph of 3 nodes
n = 6
num_qubits = n**2
tsp = Tsp.create_random_instance(n, seed=169)
adj_matrix = nx.to_numpy_matrix(tsp.graph)
print("distance\n", adj_matrix)

distance
 [[ 0.  6. 62. 31. 69. 62.]
 [ 6.  0. 57. 32. 65. 60.]
 [62. 57.  0. 78. 50. 72.]
 [31. 32. 78.  0. 62. 42.]
 [69. 65. 50. 62.  0. 31.]
 [62. 60. 72. 42. 31.  0.]]


In [23]:
#brute-force approach
from itertools import permutations
from time import time


def brute_force_tsp(w, N):
    a = list(permutations(range(1, N)))
    last_best_distance = 1e10
    for i in a:
        distance = 0
        pre_j = 0
        for j in i:
            distance = distance + w[j, pre_j]
            pre_j = j
        distance = distance + w[pre_j, 0]
        order = (0,) + i
        if distance < last_best_distance:
            best_order = order
            last_best_distance = distance
            print("order = " + str(order) + " Distance = " + str(distance))
    return last_best_distance, best_order

start = time()
best_distance, best_order = brute_force_tsp(adj_matrix, n)
print("Best order = " + str(best_order) + " with total distance = " + str(best_distance))
print(f'Time taken to run: {time() - start} seconds')

order = (0, 1, 2, 3, 4, 5) Distance = 296.0
order = (0, 1, 2, 3, 5, 4) Distance = 283.0
order = (0, 1, 2, 4, 3, 5) Distance = 279.0
order = (0, 1, 2, 4, 5, 3) Distance = 217.0
Best order = (0, 1, 2, 4, 5, 3) with total distance = 217.0
Time taken to run: 0.007005929946899414 seconds
